### ISSUE TITLE
机器人启动后每次都是前几天可以用，过了几天后就开始报错

### ISSUE THREAD

**Issue by J1angX1n** [wechaty/puppet-wechat#179]
我按照教程启动机器人后机器人每次前几天都是可以用的，过了几天后bot.Room.find就开始出问题了，之前能找得到的群名会开始返回null，下面是调用的代码和报错信息
代码：

```
bot.Room.find({topic: rn}).then(
                    room =>{
                        if(data!=""){
                            var temp = JSON.parse(data);
                            if((new Date().getTime())-(new Date(temp['date']).getTime())<3600*1000){
                                room.say(String(temp['message']));
                            }
                            
                        }
                    }
                )
```

报错信息：
13:50:44 ERR Config ###########################
13:50:44 ERR Config unhandledRejection: TypeError: Cannot read property 'say' of null
    at file:///home/paladnix/wechat-robot/examples/ding-dong-bot.js:53:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5) [object Promise]
13:50:44 ERR Config ###########################
13:50:44 ERR Config process.on(unhandledRejection) promise.catch(Cannot read property 'say' of null)
Config TypeError: Cannot read property 'say' of null
    at file:///home/paladnix/wechat-robot/examples/ding-dong-bot.js:53:38
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

**Comment by huan** [comment]
Thanks for the reporting.

I have moved this issue to puppet-wechat because it's a web protocol issue.

**Comment by J1angX1n** [comment]
> Thanks for the reporting.
> 
> I have moved this issue to puppet-wechat because it's a web protocol issue.

好的，麻烦你了，我会先去尝试换个puppet，如果还有其他的解决办法的话还望大佬可以回复我xd
