### ISSUE TITLE
Can not login with UOS patch

### ISSUE THREAD

**Issue by xiaoxintang** [wechaty/puppet-wechat#192]
```
10:02:16 INFO StarterBot onScan: Scanned(3)
10:02:17 SILL PuppetWeChatEvent onLog(checkScan() code:201 url:https://login.weixin.qq.com/qrcode/gaGsViKqww== scanCode:201)
10:02:18 SILL PuppetWeChatEvent onLog(checkScan() code:201 url:https://login.weixin.qq.com/qrcode/gaGsViKqww== scanCode:201)
10:02:19 SILL PuppetWeChatEvent onLog(checkScan() code:201 url:https://login.weixin.qq.com/qrcode/gaGsViKqww== scanCode:201)
10:02:20 SILL PuppetWeChatEvent onLog(checkScan() code:201 url:https://login.weixin.qq.com/qrcode/gaGsViKqww== scanCode:201)
10:02:21 WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
    } message:登录失败。
10:02:21 ERR Config ###########################
10:02:21 ERR Config Wechaty unhandledRejection: GError: type() {
        return this._type;
    }(登录失败。)
    at Function.from (file:///node_modules/.pnpm/registry.npmmirror.com+gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///node_modules/.pnpm/registry.npmmirror.com+wechaty-puppet-wechat@1.11.8_d4744562d843ac589ee1af4a4661bf5c/node_modules/wechaty-puppet-wechat/src/bridge.ts:189:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) [object Promise]
10:02:21 ERR Config ###########################
10:02:21 ERR Config process.on(unhandledRejection) promise.catch(type() {
        return this._type;
    }(登录失败。))
Config GError: type() {
        return this._type;
    }(登录失败。)
    at Function.from (file:///node_modules/.pnpm/registry.npmmirror.com+gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)
    at Bridge.onDialog (file:///node_modules/.pnpm/registry.npmmirror.com+wechaty-puppet-wechat@1.11.8_d4744562d843ac589ee1af4a4661bf5c/node_modules/wechaty-puppet-wechat/src/bridge.ts:189:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 2,
  details: 'GError: type() {\n' +
    '        return this._type;\n' +
    '    }(登录失败。)\n' +
    '    at Function.from (file:///node_modules/.pnpm/registry.npmmirror.com+gerror@1.0.16/node_modules/gerror/src/gerror/gerror.ts:69:17)\n' +
    '    at Bridge.onDialog (file:///node_modules/.pnpm/registry.npmmirror.com+wechaty-puppet-wechat@1.11.8_d4744562d843ac589ee1af4a4661bf5c/node_modules/wechaty-puppet-wechat/src/bridge.ts:189:31)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)'
}
```

**Comment by xiaoxintang** [comment]
the problem happen just today,without depends change

**Comment by wuwu955** [comment]
我也是这样

**Comment by wuwu955** [comment]
> the problem happen just today,without depends change

I have the same problem

**Comment by zhihualipolestar** [comment]
today I get the error too.

**Comment by starzou** [comment]
Same problem, I guess the WeChat login API has changed.

**Comment by phateffect** [comment]
> Same problem, I guess the WeChat login API has changed.

Here's the new 2.1.1 version of wechat-uos
ref: https://aur.archlinux.org/packages/wechat-uos#comment-844095

**Comment by starzou** [comment]
> 

Still failed to login.

**Comment by starzou** [comment]
> > Same problem, I guess the WeChat login API has changed.
> 
> Here's the new 2.1.1 version of wechat-uos ref: https://aur.archlinux.org/packages/wechat-uos#comment-844095

Still failed to login.

**Comment by wanguanyun** [comment]
the same problem 
hope someone can fix it

**Comment by yuanquan521** [comment]
还是不行啊， web登录不上，padlocal也登录不上

**Comment by SuMaiKaDe** [comment]
还有希望修复吗

**Comment by woostundy** [comment]
持续关注

**Comment by 156874** [comment]
持续关注

**Comment by lyxverycool** [comment]
持续关注

**Comment by LIUHanyang96** [comment]
持续关注

**Comment by azbh111** [comment]
持续关注

**Comment by huan** [comment]
Is there anyone tried to change the WECHATY_PUPPET_WECHAT_TOKEN to a customer new one, to see if it helps?

See

- https://github.com/wechaty/puppet-wechat/pull/142

**Comment by vanplus** [comment]
> 

My code:

```js
process.env.WECHATY_PUPPET_SERVICE_TOKEN = process.env.WECHATY_PUPPET_WECHAT_TOKEN = token

WechatyBuilder.build({
    name: 'wechaty-puppet-wechat',
    puppet: 'wechaty-puppet-wechat',
    puppetOptions: {
      token: process.env.WECHATY_PUPPET_WECHAT_TOKEN,
    }
})
```

Result:
```
WARN PuppetWeChatBridge onDialog() page.on(dialog) type:type() {
        return this._type;
} message:登录失败。
```

**Comment by JoffreyN** [comment]
用不了了？有希望吗？

**Comment by vanplus** [comment]
https://web.wechat.com/ 可以直接登录

**Comment by azbh111** [comment]
> https://web.wechat.com/ 可以直接登录

不行，登录不了

**Comment by JoffreyN** [comment]
对于不能登录网页版的微信  是无解了吗？

**Comment by azbh111** [comment]
自建puppet-service，还需要购买token吗？
如果需要购买，那么为什么要自建呢？

**Comment by vanplus** [comment]
> > https://web.wechat.com/ 可以直接登录
> 
> 不行，登录不了

我的号能登录，就是自定义 extspam  不行。说不定你的号就行呢。

> 通过 [BlueSky-07/wechat-token](https://github.com/BlueSky-07/wechat-token) 获取 extspam
> 
> My code:
> 
> ```js
> const extspam = GET_FROM('https://github.com/BlueSky-07/wechat-token')
> process.env.WECHATY_PUPPET_WECHAT_TOKEN = extspam
> 
> WechatyBuilder.build({
>     name: 'wechaty-puppet-wechat',
>     puppet: 'wechaty-puppet-wechat',
>     puppetOptions: {
>       token: process.env.WECHATY_PUPPET_WECHAT_TOKEN,
>     }
> })
> ```

**Comment by azbh111** [comment]
> > > https://web.wechat.com/ 可以直接登录
> > 
> > 
> > 不行，登录不了
> 
> 我的号能登录，就是自定义 extspam 不行。说不定你的号就行呢。
> 
> > 通过 [BlueSky-07/wechat-token](https://github.com/BlueSky-07/wechat-token) 获取 extspam
> > My code:
> > ```js
> > const extspam = GET_FROM('https://github.com/BlueSky-07/wechat-token')
> > process.env.WECHATY_PUPPET_WECHAT_TOKEN = extspam
> > 
> > WechatyBuilder.build({
> >     name: 'wechaty-puppet-wechat',
> >     puppet: 'wechaty-puppet-wechat',
> >     puppetOptions: {
> >       token: process.env.WECHATY_PUPPET_WECHAT_TOKEN,
> >     }
> > })
> > ```

哎，这个方法我还是不行，应该和账号有关系

**Comment by SuMaiKaDe** [comment]
> > > > https://web.wechat.com/ 可以直接登录
> > > 
> > > 
> > > 不行，登录不了
> > 
> > 
> > 我的号能登录，就是自定义 extspam 不行。说不定你的号就行呢。
> > > 通过 [BlueSky-07/wechat-token](https://github.com/BlueSky-07/wechat-token) 获取 extspam
> > > My code:
> > > ```js
> > > const extspam = GET_FROM('https://github.com/BlueSky-07/wechat-token')
> > > process.env.WECHATY_PUPPET_WECHAT_TOKEN = extspam
> > > 
> > > WechatyBuilder.build({
> > >     name: 'wechaty-puppet-wechat',
> > >     puppet: 'wechaty-puppet-wechat',
> > >     puppetOptions: {
> > >       token: process.env.WECHATY_PUPPET_WECHAT_TOKEN,
> > >     }
> > > })
> > > ```
> 
> 哎，这个方法我还是不行，应该和账号有关系

应该和账号有关系。
前段时间网页文件传输刚出来，登录一次网页文件传输助手，就可以登录网页版微信。
后悔当时觉得可以用uos就没登录。
结果转眼就封了uos，web也登不上。

**Comment by hxianseng** [comment]
> > > > > https://web.wechat.com/ 可以直接登录
> > > > 
> > > > 
> > > > 不行，登录不了
> > > 
> > > 
> > > 我的号能登录，就是自定义 extspam 不行。说不定你的号就行呢。
> > > > 通过 [BlueSky-07/wechat-token](https://github.com/BlueSky-07/wechat-token) 获取 extspam
> > > > My code:
> > > > ```js
> > > > const extspam = GET_FROM('https://github.com/BlueSky-07/wechat-token')
> > > > process.env.WECHATY_PUPPET_WECHAT_TOKEN = extspam
> > > > 
> > > > WechatyBuilder.build({
> > > >     name: 'wechaty-puppet-wechat',
> > > >     puppet: 'wechaty-puppet-wechat',
> > > >     puppetOptions: {
> > > >       token: process.env.WECHATY_PUPPET_WECHAT_TOKEN,
> > > >     }
> > > > })
> > > > ```
> > 
> > 
> > 哎，这个方法我还是不行，应该和账号有关系
> 
> 应该和账号有关系。 前段时间网页文件传输刚出来，登录一次网页文件传输助手，就可以登录网页版微信。 后悔当时觉得可以用uos就没登录。 结果转眼就封了uos，web也登不上。
我微信有web权限，能用吗？

**Comment by coronin** [comment]
关注

**Comment by linrol** [comment]
持续关注

**Comment by vanplus** [comment]
既然新版统信 UOS 和银河麒麟微信仍然基于 electron, 那么我们可以研究下新版 API 的变化

[腾讯出了 Linux 版微信~ - V2EX](https://www.v2ex.com/t/825417)

**Comment by SouthTass** [comment]
持续关注，希望能继续使用

**Comment by SuMaiKaDe** [comment]
> 既然新版统信 UOS 和银河麒麟微信仍然基于 electron, 那么我们可以研究下新版 API 的变化
> 
> [腾讯出了 Linux 版微信~ - V2EX](https://www.v2ex.com/t/825417)

这次也是electron封装的？

**Comment by xiaogaozi** [comment]
来自其它社区的相关讨论：https://github.com/ehForwarderBot/efb-wechat-slave/issues/126

**Comment by zicheng-jscoder** [comment]
每天来一遍

**Comment by dazhi1011** [comment]
持续关注

**Comment by fulln** [comment]
用docker 登陆后提示{"data":"Unable to log in"})

**Comment by BZever** [comment]
持续关注

**Comment by LIUHanyang96** [comment]
有什么进展吗

**Comment by 156874** [comment]
好像还没好

**Comment by PonyC** [comment]
持续关注

**Comment by huan** [comment]
UOS patch does not work after Jan 1, 2022, so we have a PR to disable it by default:

- #193 

So that we can use the origin web protocol for very limited accounts.

You can still enable the UOS patch by set `WECHATY_PUPPET_WECHAT_UOS=true`, learn more from the above issue and related PR

- #196

**Comment by smartnikocj** [comment]
是不是还没有解决呀？

**Comment by aote777** [comment]
等待中

**Comment by lx0758** [comment]
挖坟

**Comment by JS-banana** [comment]
mark

**Comment by huan** [comment]
## Update: recommend using Wechaty Puppet XP

It seems that the UOS patch has no solution to be enabled again. (If anyone has a solution, please submit a PR)

So for users who need a free Wechaty Puppet Provider (WPP), we are suggesting that you can try the [Wechaty Puppet XP](https://github.com/wechaty/puppet-xp) which is a free WPP based on the Windows WeChat Client.

I will lock this thread for now. Please file a new issue if there's any need.

**Comment by leochen-g** [comment]
## good news, uos great again

Please follow this pr #206

**Comment by leochen-g** [comment]
现在可以安装最新版进行uos桌面版体验了 `npm install wechaty-puppet-wechat@latest --save`，注意查看版本是`1.18.4` ,如果安装失败，记得把npm源切换为`https://registry.npmjs.org/`，其他源可能还没同步。同时代码里需要开启uos选项，默认是关闭的，参考以下配置：
```
const bot = WechatyBuilder.build({
    name: 'puppet-wechat',
    puppetOptions: {
      uos: true  // 开启uos协议
    },
    puppet: 'wechaty-puppet-wechat',
})

```
