### ISSUE TITLE
启动失败，疑似chrome-linux模块兼容性问题

### ISSUE THREAD

**Issue by atorber** [wechaty/puppet-wechat#213]
03:10:27 ERR PuppetWeChat initBridge() exception: Failed to launch the browser process!
/workspace/wechat-openai-qa-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

03:10:27 ERR PuppetWeChat initBridge() this.bridge.stop() rejection: Error: no page
03:10:27 ERR {"code":2,"details":"Error: Failed to launch the browser process!\n/workspace/wechat-openai-qa-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/workspace/wechat-openai-qa-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)\n    at Interface.<anonymous> (/workspace/wechat-openai-qa-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)\n    at Interface.emit (node:events:525:35)\n    at Interface.emit (node:domain:489:12)\n    at Interface.close (node:readline:590:8)\n    at Socket.onend (node:readline:280:10)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)","message":"Failed to launch the browser process!\n/workspace/wechat-openai-qa-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n","name":"Error","stack":"Error: Failed to launch the browser process!\n/workspace/wechat-openai-qa-bot/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: error while loading shared libraries: libatk-1.0.so.0: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md\n\n    at onClose (/workspace/wechat-openai-qa-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:268:9)\n    at Interface.<anonymous> (/workspace/wechat-openai-qa-bot/node_modules/puppeteer/src/node/BrowserRunner.ts:254:50)\n    at Interface.emit (node:events:525:35)\n    at Interface.emit (node:domain:489:12)\n    at Interface.close (node:readline:590:8)\n    at Socket.onend (node:readline:280:10)\n    at Socket.emit (node:events:525:35)\n    at Socket.emit (node:domain:489:12)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)"}

**Comment by atorber** [comment]
Ubuntu

**Comment by atorber** [comment]
> Ubuntu
尝试运行安装缺失依赖可以修复，对应上述报错 `sudo apt install libatk-1.0.so.0`，如果还有其他依赖确实，逐个安装

```
sudo apt install gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget libgbm1
```
