### ISSUE TITLE
login timeout with UOS

### ISSUE THREAD

**Issue by HyperClockUp** [wechaty/puppet-wechat#214]
I can use it normally before, but it suddenly can not send/receive msg today.

After that I logout my account and try to login, the error comes as following:

```
this.puppet.emit('error', new Error(
                                ^
GError: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"
    at Watchdog.reset (/home/ubuntu/projects/wechaty-wechat/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)
    at Watchdog.emit (node:events:390:28)
    at Watchdog.emit (node:domain:475:12)
    at Timeout._onTimeout (/home/ubuntu/projects/wechaty-wechat/node_modules/wechaty-puppet/node_modules/watchdog/src/watchdog.ts:115:12)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 2,
  details: 'Error: WatchdogAgent reset: lastFood: "{"data":"heartbeat@browserbridge ding","timeoutMilliseconds":60000}"\n' +
    '    at Watchdog.reset (/home/ubuntu/projects/wechaty-wechat/node_modules/wechaty-puppet/src/agents/watchdog-agent.ts:65:33)\n' +
    '    at Watchdog.emit (node:events:390:28)\n' +
    '    at Watchdog.emit (node:domain:475:12)\n' +
    '    at Timeout._onTimeout (/home/ubuntu/projects/wechaty-wechat/node_modules/wechaty-puppet/node_modules/watchdog/src/watchdog.ts:115:12)\n' +
    '    at listOnTimeout (node:internal/timers:557:17)\n' +
    '    at processTimers (node:internal/timers:500:7)'
```

**Comment by HyperClockUp** [comment]
it seems like my account was banned, change my password every is ok

**Comment by HyperClockUp** [comment]
it seems like my account was banned, change my password everything is going ok
