### ISSUE TITLE
ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env

### ISSUE THREAD

**Issue by pickmonster** [wechaty/puppet-wechat#228]
02:17:53 INFO StarterBot Starter Bot Started.
02:17:54 INFO StarterBot onScan: Waiting(2) - https://wechaty.js.org/XXXXXXXXXX
02:18:08 INFO StarterBot onScan: Scanned(3)
02:18:17 ERR PuppetWeChatBridge onLoad() exception: Error: execute proxyWechaty(init) error: 503, init() without a ready angular env
D:\develop\wechaty\big-king-wechaty\node_modules\wechaty-puppet-wechat\src\bridge.ts:356
        throw new Error('execute proxyWechaty(init) error: ' + retObj?.code + ', ' + retObj?.message)
              ^
GError: execute proxyWechaty(init) error: 503, init() without a ready angular env
    at Bridge.inject (D:\develop\wechaty\big-king-wechaty\node_modules\wechaty-puppet-wechat\src\bridge.ts:356:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Bridge.onLoad (D:\develop\wechaty\big-king-wechaty\node_modules\wechaty-puppet-wechat\src\bridge.ts:214:7) {
  code: 2,
  details: 'Error: execute proxyWechaty(init) error: 503, init() without a ready angular env\n' +
    '    at Bridge.inject (D:\\develop\\wechaty\\big-king-wechaty\\node_modules\\wechaty-puppet-wechat\\src\\bridge.ts:356:15)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
    '    at async Bridge.onLoad (D:\\develop\\wechaty\\big-king-wechaty\\node_modules\\wechaty-puppet-wechat\\src\\bridge.ts:214:7)'
}

It can be started normally, but an error is reported after scanning the WeChat code to log in.

This is package.json file
```shell
{
  "name": "wechat-bot",
  "version": "1.0.0",
  "description": "",
  "main": "main.ts",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "cross-env WECHATY_LOG=verbose WECHATY_PUPPET=wechaty-puppet-wechat npx ts-node main.ts"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "axios": "^1.5.1",
    "dotenv": "^16.3.1",
    "qrcode-terminal": "^0.12.0",
    "wechaty": "^1.20.2",
    "wechaty-puppet-wechat4u": "^1.14.6"
  },
  "devDependencies": {
    "@types/node": "^20.8.7",
    "@types/qrcode-terminal": "^0.12.1",
    "cross-env": "^7.0.3",
    "ts-node": "^10.9.1",
    "typescript": "^5.2.2"
  },
  "git": {
    "scripts": {
      "pre-push": "npx git-scripts-pre-push"
    }
  },
  "engines": {
    "node": ">= 16",
    "npm": ">=7"
  }
}

```

**Comment by yahao333** [comment]
I have the same question

**Comment by shiyeling** [comment]
我也是一样的问题。从这个[https://github.com/wechaty/wechaty/issues/603](url)看起来，好像老早以前就有的问题，不确定我欸什么UOS没有解决
